version: "2"

services:
  rasterfari:
    container_name: rasterfari
    image: cismet/rasterfari-wms:latest
    network_mode: bridge
    ports:
      - 8081:8081
      - 9229:9229
    volumes:
      - ./config.json:/app/config.json:ro
      - ./dirConfigs.json:/app/dirConfigs.json:ro
      #- ./docs:/app/docs:ro
      - ./policy.xml:/etc/ImageMagick-6/policy.xml:ro
      - ./tmp:/app/tmp
      - ./cache:/app/cache

      - ./docs/bplaene:/app/bplaene:ro
      - ./docs/vermessungsregister:/app/vermessungsregister:ro
      - ./docs/Baulasten:/app/Baulasten:ro
      - ./docs/baulasten_rs:/app/docs:ro
      - ./docs/qsgeb:/app/qsgeb:ro

      ## use this only in dev
      - ./package.json:/app/package.json
      - ./custom.js:/app/custom.js
      - ./server.js:/app/server.js
      - ./logs:/app/logs
      - ./app.json:/app/app.json
    restart: always
    ## the default command will run rasterfari with 20 threads

    # command: "yarn run production-run"
    command: /bin/bash -c "sleep infinity"
    #command: "yarn start"
