version: '2'

services:

 rasterfari-wms:
  container_name: rasterfari-wms
  image: cismet/rasterfari-wms:latest
  network_mode: bridge
  ports:
   - 8081:8081
  volumes:
   - ./config.json:/app/config.json:ro
   - ./dirConfigs.json:/app/dirConfigs.json:ro
   - ./docs:/app/docs:ro
   - ./policy.xml:/etc/ImageMagick-6/policy.xml:ro
   - ./tmp:/app/tmp
   - ./cache:/app/cache
   ## use this only in dev
   - ./custom.js:/app/custom.js
   - ./server.js:/app/server.js
   - ./logs:/app/logs
  restart: always
  ## the default command will run rasterfari with 20 threads
  #command: yarn run dev-run
